name: SGAE Backend CI

on:
  push:
    branches: [ "main", "security" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration du JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilation et Exécution des Tests
        run: mvn clean verify -X

      - name: Upload du JAR (Artefact)
        # Cette étape ne s'exécutera QUE si les tests passent
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sgae-api-validated
          path: target/*.jar